### ISSUE TITLE
Replicate METviewer Reliability diagram using Python

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplotpy#12]
Replicate this type of plot from threshold, pstd_calibration, pstd_baser, pstd_ni.
 
![plot_20190904_142544](https://user-images.githubusercontent.com/23195803/64264057-eb31ef00-ceed-11e9-97fc-f2f7e3a12a8d.png)

**Comment by JohnHalleyGotway** [comment]
At the NOAA METplus User Telecon on 11/2/2020, Binyu requested that the location of the "Reliability Event Histogram" be made configurable:
https://docs.google.com/document/d/1eexZnfoBnJL6kmevDfgK0f29hm_tw3Pb0-9FzU3ACnM/edit

"On the “Reliability diagram”, can we have the option to move “Reliability Event Histogram” to the upper left corner instead of having some giant bar covering a big part of the major lines."

Please include this option when implementing the reliability diagram in METplotpy.

Example:
https://www.emc.ncep.noaa.gov/users/meg/hrefv3/verif/href/radar/hrefv3_spc_prob_REFC_gt40_reliability.png

Binbin also suggests renaming “Reliability Event Histogram” as “Sharpness” to be consistent with existing conventions.
