### ISSUE TITLE
Incorrect Roc plot

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METplotpy#85]
## Describe the Problem ##
*Plot that is generated by metplotpy is different from the one that was generated by R.
[plot_20210203_210233.xml.txt](https://github.com/dtcenter/METplotpy/files/5945884/plot_20210203_210233.xml.txt)
[plot_20210203_210233.data.txt](https://github.com/dtcenter/METplotpy/files/5989662/plot_20210203_210233.data.txt)
[plot_20210203_210233.yaml.txt](https://github.com/dtcenter/METplotpy/files/5989663/plot_20210203_210233.yaml.txt)
Rscript pofd values (x coordinates): 1.000000000 0.009094773 0.051334613 0.094744956 0.121377046 0.000000000
Rscript pody values (y coordinates): 1.0000000 0.1416201 0.6079951 0.8340595 0.8921212 0.0000000

![plot_20210208_182414](https://user-images.githubusercontent.com/21346768/107264522-4b409500-6a00-11eb-970a-410fb89a43a7.png)
![plot_20210208_182521](https://user-images.githubusercontent.com/21346768/107264581-5d223800-6a00-11eb-8338-62a47d76a1a8.png)

*

### Expected Behavior ###
*Plots have to  match*

### Environment ###
Describe your runtime environment:
*1. https://metviewer.nws.noaa.gov/metviewer_dev/*
*2. 20210203_210233*

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
2790541

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by bikegeek** [comment]
The issue appears when using CTC input data, which has fcst_thresh values that contain comparison operators: >,<, >=,<=, and ==.  The Python implementation initially didn't include the code that sorts the dataframe based on fcst_thresh values.  Naively implementing the Python equivalent of sorting based on fcst_thresh values fails when pandas attempts to sort fcst_thresh when there is a comparison operator with a numerical value (i.e. >0.1,  ==35, <=100).  Follow the threshold sorting logic used by Java:
https://github.com/dtcenter/METviewer/blob/04979b687470706baed4ea67e7fb54a35bf0a55e/java/edu/ucar/metviewer/MVUtil.java#L1103

**Comment by bikegeek** [comment]
Upon deeper investigation, the 'incorrect' plot has multiple points of the same value.  This is traced back to ctc_statistics (METcalcpy) implementation of calculate_ctc_roc(subsetted_df) which invokes calculate_pody(np_2d, columns). Where np_2d is the 2D numpy representation of the data (ie no header information) and columns is a list of all the column names (one way to capture the header information).    This in turn incorrectly invokes METcalcpy's sum_column_data_by_name() which generates the sum of the column of interest, not the entire column of interest, which is what we want.  

**What we want to calculate is the equivalent of the R-implementation:**
_dfROC$pody = dfROC$fy_oy / (dfROC$fy_oy + dfROC$fn_oy);
dfROC$pofd = dfROC$fy_on / (dfROC$fy_on + dfROC$fn_on);_

**Python implementation (incorrect):**
_fy_oy = sum_column_data_by_name(input_data, columns_names, 'fy_oy')
fn_oy = sum_column_data_by_name(input_data, columns_names, 'fn_oy')
oy = fy_oy + fn_oy
result = fy_oy / oy
result = round_half_up(result, PRECISION)_

Instead of invoking sum_column_data_by_name(), we want a method get_column_data_by_name() which uses the same input as sum_column_data_by_name() and uses most of the same logic (except for dealing with NaN values and returning an np-array rather than a singular value)

**Comment by bikegeek** [comment]
Now there are issues with divide by zero in calculating the pody and pofd values.  The denominator for pody is zero when fy_oy and fn_oy values are BOTH 0.  Likewise, the denominator for the pofd value is zero when fy_on and fn_on are zero.  Inspecting the data used (above link) reveals that we have rows where we have these columns equal to zero.

**Comment by bikegeek** [comment]
Changes are in the feature_11_ROC_diagram feature branch.  Closing this issue.
